### ISSUE TITLE
fetching linker genes does not work when using Cytoscape ReactomeFI in ubuntu

### ISSUE THREAD

**Issue by jpinero** [reactome-fi/CytoscapePlugIn#15]
Hi, 
since the previous version of the app, we have been encountering issues with using the gene set analysis. I use as an input a list of 18 genes, identified by symbols, and the app stays forever like this
![image](https://user-images.githubusercontent.com/2444472/114302307-ca1d8100-9ac8-11eb-8a1a-7fdbc3d027f0.png)
even when it is obvious that it has already loaded the data. 
in the console you can see lots of lines like these
Exception in thread "AWT-EventQueue-0" java.util.concurrent.CompletionException: java.lang.ClassCastException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException
Exception in thread "AWT-EventQueue-0" java.util.concurrent.CompletionException: java.lang.ClassCastException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecut

best
janet

**Comment by guanmingwu** [comment]
Hi Janet,

The bug has been fixed now. Could you please update your app to version 8.0.2?

Thanks a lot for reporting this and using our app.

Guanming

**Comment by jpinero** [comment]
thanks a lot! it works perfectly now. 
best 
janet
