### ISSUE TITLE
problem converting pathway network to FI network

### ISSUE THREAD

**Issue by jpinero** [reactome-fi/CytoscapePlugIn#16]
Hi again!
now I performed a pathway enrichment and selected one of the branches. When I click on convert to FI network, I get this error
![image](https://user-images.githubusercontent.com/2444472/114389751-aecc7780-9b95-11eb-8f73-8ec21feabf9f.png)

and this message in the console

ava.net.UnknownHostException: cpws.reactome.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at java.net.Socket.connect(Socket.java:558) ~[?:?]
	at java.net.Socket.<init>(Socket.java:454) ~[?:?]
	at java.net.Socket.<init>(Socket.java:306) ~[?:?]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80) ~[?:?]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122) ~[?:?]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[?:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[?:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[?:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[?:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[?:?]
	at org.reactome.cytoscape.util.PlugInUtilities.callHttp(PlugInUtilities.java:1095) ~[?:?]
	at org.reactome.cytoscape.util.PlugInUtilities.callHttpInXML(PlugInUtilities.java:1021) ~[?:?]
	at org.reactome.cytoscape.service.RESTFulFIService.queryInteractions(RESTFulFIService.java:273) ~[?:?]
	at org.reactome.cytoscape.service.RESTFulFIService.convertPathwayToFIs(RESTFulFIService.java:152) ~[?:?]
	at org.reactome.cytoscape.pathway.DiagramAndNetworkSwitcher.convertPathwayToFINetwork(DiagramAndNetworkSwitcher.java:148) ~[?:?]
	at org.reactome.cytoscape.pathway.DiagramAndNetworkSwitcher.access$0(DiagramAndNetworkSwitcher.java:138) ~[?:?]
	at org.reactome.cytoscape.pathway.DiagramAndNetworkSwitcher$2.run(DiagramAndNetworkSwitcher.java:105) ~[?:?]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321) ~[93:org.cytoscape.work-swing-impl:3.8.2]

could you help, please?
thanks!

**Comment by guanmingwu** [comment]
This should be fixed now with the new release of ReactomeFIViz, 8.0.3, at App Store. The use of Java 11 exposes some quite cast exceptions among numbers. There are may be some issues existing. Sorry!

**Comment by jpinero** [comment]
Great! it is working perfectly now. Thank you so much!
